# Generated by Django 4.1 on 2022-08-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_osinfofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osinfofile',
            name='output',
            field=models.FileField(blank=None, upload_to='osinfo/output'),
        ),
    ]
