# Generated by Django 4.1 on 2022-08-24 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExcelDocument',
        ),
        migrations.DeleteModel(
            name='FileMode',
        ),
    ]
