# Generated by Django 4.1 on 2022-08-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_osinfofile_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osinfofile',
            name='output',
            field=models.FileField(blank=True, upload_to='osinfo/output'),
        ),
    ]
